Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/trusty64"
  
	config.vm.define "dockerdaemon" do |dockerdaemon|
		dockerdaemon.vm.hostname = "dockerdaemon"
		dockerdaemon.vm.network :private_network, ip: "172.31.0.220" 
		config.vm.synced_folder "./Shared", "/vagrant", type: "smb"
		dockerdaemon.vm.provision "docker", type: "shell", path: "setup-docker.sh"
	end

end