Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/trusty64"
  
	config.vm.define "rubydev" do |dockerdaemon|
		dockerdaemon.vm.hostname = "rubydev"
		dockerdaemon.vm.network :private_network, ip: "172.31.0.67"
		dockerdaemon.vm.provision "ruby", type: "shell", path: "setup-ruby.sh"
	end

end